### ISSUE TITLE
SVG loading in external project fails

### ISSUE THREAD

**Issue by kbrabrand** [netliferesearch/dfo-storybook#4]
By default webpack won't transpile stuff from `node_modules`. In the examples we've shown how to get around it for vanilla react projects with webpack. In the next example a workaround for transpiling the @dfo/components package is shown, but it has problems with svg files in the package.

Need to dig to find out how to get past it in next as well.

**Comment by nilsnh** [comment]
Closing this as I haven't seen this bug in a while, and it might come from misconfigurations in the consumer.
